config/routes.rb
Rails.application.routes.draw do

  devise_for :accounts

  get '/browse' => 'browse#browse', as: :browse

  root to: 'public#home'

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many_attached :images

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise, if: :devise_controller?

  private

  def configure_devise
    devise_parameter_sanitizer.permit(:account_update, keys: [ :first_name, :last_name, :username, images: [] ])
  end
  
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController

  def browse
    @users = Account.where.not(id: current_account.id)
  end

  def approve
    # user swipes right
  end

  def decline
    # user swipes left
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/browse/browse.html.erb
<ul id="slides">
  <% @users.each_with_index do |user, i| %>
    <div class="slide <%= 'showing' if i == 0 %>" data-id="<%= user.id %>">
      <li><%= user.first_name %></li>
    </div>
  <% end %>
</ul>

<div id="slide-controls">
  <span id="decline"><i class="fa fa-times-circle fa-2x"></i></span>
  <span id="approve"><i class="fa fa-heart fa-2x"></i></span>
</div>

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <div class="row">
    <div class="col-12 col-md">
      <small class="d-block mb-3 text-muted">© 2017-2019</small>
    </div>
    <div class="col-4 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
        <li><a class="text-muted" href="#">Another one</a></li>
        <li><a class="text-muted" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-4 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-4 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Tinder C</h5>

  <% if account_signed_in? %>
    <nav class="my-2 my-md-0 mr-md-3">
      <%= link_to 'Browse', browse_path, class: "text-dark mr-3" %>
      <%= link_to 'My Matches', '#', class: "text-dark mr-3" %>
      <%= link_to 'Settings', edit_account_registration_path, class: "text-dark mr-3" %>
    </nav>

    <%= link_to 'Sign out', destroy_account_session_path, method: :delete, class: "btn btn-outline-dark" %>
  <% else %>
    <nav class="my-2 my-md-0 mr-md-3">
      <a class="p-2 text-dark" href="#">Features</a>
      <a class="p-2 text-dark" href="#">Pricing</a>
      <a class="p-2 text-dark" href="#">Support</a>
    </nav>

    <%= link_to 'Sign in', new_account_session_path, class: "btn btn-secondary mr-3" %>
    <%= link_to 'Sign up', new_account_registration_path, class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinderC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>